services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle
    restart: unless-stopped
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - /docker-data/oracle:/opt/oracle/oradata
    networks:
      - data-net
    ports:
      - "1521:1521"

networks:
  data-net:
    external: true