services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - /docker-data/minio:/data
    networks:
      - data-net
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  data-net:
    external: true